version: 3

env:
  BUILD_TAGS: kloudlite
  LDFLAGS: "-s -w"

tasks:
  build:
    cmds:
      - make build
      - |+
        if command -v upx 2>&1 > /dev/null; then
          upx ./cluster-autoscaler-amd64
        fi

  docker:build:
    preconditions:
      - sh: '[[ ! -z "{{.TAG}}" ]]'
        msg: 'var TAG must be set'
    vars:
      IMAGE: ghcr.io/kloudlite/cluster-autoscaler
    cmds:
      - task: build
      - |+
        GOARCH=$(go env GOARCH)
        make make-image IMAGE="{{.IMAGE}}" TAG={{.TAG}}
        docker tag {{.IMAGE}}-$GOARCH:{{.TAG}} {{.IMAGE}}:{{.TAG}}
        docker push {{.IMAGE}}:{{.TAG}}

  run:
    env:
      GOARCH: amd64
    preconditions:
      - sh: '[[ ! -z "$KUBECONFIG" ]]'
        msg: 'env var KUBECONFIG must be set'
    cmds:
      - task: build
      - ./cluster-autoscaler-$GOARCH --kubeconfig="$KUBECONFIG" --cloud-provider=kloudlite --logtostderr=true --stderrthreshold=info -v=4 --expander=random --scale-down-unneeded-time 1m
